/* ============================================================
   EagleEyE — fundamentals.js
   Real financial data sourced from:
   - Annual reports (africanfinancials.com)
   - SIC Brokerage Stock Recommendation Report Q4 2025
   - Simply Wall St GSE market analysis
   - African Markets company profiles
   Last updated: June 2026
   ============================================================ */

const GSE_FUNDAMENTALS = {

  GCB: {
    fullName: 'GCB Bank PLC',
    sector: 'Banking',
    description: 'Ghana\'s largest indigenous bank by assets, with over 180 branches nationwide. Dominant in retail and corporate banking.',
    // From 2025 Annual Report
    eps: 7.78,             // GHS — FY2025
    bookValue: 17.96,      // GHS per share (shareholders equity / shares outstanding)
    roe: 39.0,             // % return on equity
    dividendPerShare: 2.80,// GHS — FY2025 recommended dividend
    revenueGrowth: 40.9,   // % operating income growth YoY
    profitGrowth: 117.2,   // % profit growth YoY (9M 2025)
    nplRatio: 10.3,        // % non-performing loans
    car: 18.0,             // % capital adequacy ratio
    forwardPE: 2.12,       // analyst estimate
    priceTarget: 28.96,    // GHS — SIC Brokerage target
    recommendation: 'BUY',
    analystNote: 'Trading at P/B of 0.94x suggesting undervaluation. Strong profit growth of 117% YoY. CAR well above regulatory minimum.',
    dataSource: 'SIC Brokerage Q4 2025 Report & GCB 2025 Annual Report',
    lastUpdated: 'Mar 2026',
  },

  MTNGH: {
    fullName: 'MTN Ghana Ltd',
    sector: 'Telecom',
    description: 'Ghana\'s largest mobile operator with over 29 million subscribers. Dominant in mobile money (MoMo) and data services.',
    eps: 0.56,
    bookValue: 1.20,
    roe: 46.7,
    dividendPerShare: 0.40, // FY2025 final dividend paid April 2026
    revenueGrowth: 22.0,
    profitGrowth: 30.0,
    nplRatio: null,
    car: null,
    forwardPE: 11.6,
    priceTarget: 5.89,     // analyst price target
    recommendation: 'HOLD',
    analystNote: 'Dividend yield of 0.7% below industry average. EPS steady. Analysts expect 30% earnings growth over next 5 years. Stock up 272% over past year — valuation approaching fair value.',
    dataSource: 'Simply Wall St GSE Analysis & SIC Brokerage',
    lastUpdated: 'Jun 2026',
  },

  EGH: {
    fullName: 'Ecobank Ghana PLC',
    sector: 'Banking',
    description: 'A subsidiary of Ecobank Transnational Inc., one of Ghana\'s largest banks by total assets.',
    eps: 10.45,
    bookValue: 28.10,
    roe: 37.2,
    dividendPerShare: 1.1132, // annual dividend payable July 2026
    revenueGrowth: 46.8,
    profitGrowth: 45.6,
    nplRatio: 20.96,
    car: 19.1,
    forwardPE: 3.29,
    priceTarget: 32.26,
    recommendation: 'BUY',
    analystNote: 'Profit after tax up 45.6% YoY. High NPL ratio (21%) is a risk. Dividend of GHS 1.11 announced June 2026. Strong shareholder equity growth of 44.8%.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jun 2026',
  },

  ETI: {
    fullName: 'Ecobank Transnational Inc.',
    sector: 'Banking',
    description: 'Pan-African banking group operating across 33 African countries. Largest banking network on the continent.',
    eps: 0.014,
    bookValue: 0.45,
    roe: 15.2,
    dividendPerShare: 0.015,
    revenueGrowth: 12.0,
    profitGrowth: -88.3,   // EPS fell from GHS 0.12 to GHS 0.014 in FY2025
    nplRatio: null,
    car: null,
    forwardPE: 162.0,      // very high due to earnings drop
    priceTarget: 1.80,
    recommendation: 'HOLD',
    analystNote: 'EPS dropped sharply from GHS 0.12 to GHS 0.014 in FY2025 — significant earnings deterioration. Monitor closely. Pan-African diversification provides some stability.',
    dataSource: 'Simply Wall St GSE Analysis',
    lastUpdated: 'Jun 2026',
  },

  SIC: {
    fullName: 'SIC Insurance Company Ltd',
    sector: 'Insurance',
    description: 'Ghana\'s largest state-owned insurance company. Offers general and life insurance products.',
    eps: 0.28,
    bookValue: 1.20,
    roe: 23.3,
    dividendPerShare: 0.05,
    revenueGrowth: 18.0,
    profitGrowth: 25.0,
    nplRatio: null,
    car: null,
    forwardPE: 20.0,
    priceTarget: 4.80,
    recommendation: 'HOLD',
    analystNote: 'Stock up significantly YTD on speculative buying. Earnings need to catch up with price. Watch for upcoming annual results.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jun 2026',
  },

  GOIL: {
    fullName: 'GOIL Company Ltd',
    sector: 'Energy',
    description: 'Ghana\'s largest indigenous petroleum products distribution company with a nationwide retail network.',
    eps: 0.80,
    bookValue: 3.50,
    roe: 22.9,
    dividendPerShare: 0.30,
    revenueGrowth: 15.0,
    profitGrowth: 20.0,
    nplRatio: null,
    car: null,
    forwardPE: 9.4,
    priceTarget: 9.50,
    recommendation: 'BUY',
    analystNote: 'Consistent dividend payer. Beneficiary of Ghana\'s growing fuel consumption. Trading below estimated fair value.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jun 2026',
  },

  RBGH: {
    fullName: 'Republic Bank Ghana Ltd',
    sector: 'Banking',
    description: 'Mid-tier commercial bank with strong retail and SME banking presence.',
    eps: 0.50,
    bookValue: 2.80,
    roe: 17.9,
    dividendPerShare: 0.046, // GHS 0.0460 per share recommended FY2025
    revenueGrowth: 20.8,
    profitGrowth: 36.6,
    nplRatio: 14.15,
    car: 20.15,
    forwardPE: 1.52,
    priceTarget: 1.20,
    recommendation: 'BUY',
    analystNote: 'Profit After Tax grew 36.6% YoY. CAR strong at 20.15%. NPL improving from 15.64% to 14.15%. Trading at a significant discount to book value.',
    dataSource: 'RBGH 2025 Annual Report via AfricanFinancials',
    lastUpdated: 'Feb 2026',
  },

  KASAPREKO: {
    fullName: 'Kasapreko Company PLC',
    sector: 'Consumer Goods',
    description: 'Leading Ghanaian beverage and pharmaceutical company. IPO in May 2026 raised GH₵1.72 billion — largest manufacturing IPO in Ghana\'s history.',
    eps: 0.18,
    bookValue: 1.05,
    roe: 17.1,
    dividendPerShare: 0.05,
    revenueGrowth: 32.0,
    profitGrowth: 28.0,
    nplRatio: null,
    car: null,
    forwardPE: 10.6,
    priceTarget: 2.50,
    recommendation: 'BUY',
    analystNote: 'Recent IPO raised $147M — strong investor confidence. Revenue growth of 32% YoY. Dominant local brand with expansion plans. Stock appreciated 9.95% on June 22.',
    dataSource: 'Accra Street Journal IPO Coverage Jun 2026',
    lastUpdated: 'Jun 2026',
  },

  CAL: {
    fullName: 'CalBank PLC',
    sector: 'Banking',
    description: 'Commercial bank focused on retail, SME and corporate banking services.',
    eps: 0.10,
    bookValue: 0.58,
    roe: 17.2,
    dividendPerShare: 0.03,
    revenueGrowth: 14.0,
    profitGrowth: 12.0,
    nplRatio: 18.5,
    car: 14.2,
    forwardPE: 7.3,
    priceTarget: 1.00,
    recommendation: 'HOLD',
    analystNote: 'Trading below book value. High NPL ratio remains a concern. Capital adequacy close to regulatory minimum. Recovery dependent on broader credit quality improvement.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jan 2026',
  },

  GGBL: {
    fullName: 'Guinness Ghana Breweries Ltd',
    sector: 'Consumer Goods',
    description: 'Ghana\'s leading brewer and distiller, subsidiary of Diageo. Produces Guinness, Malta, Smirnoff, and other brands.',
    eps: 0.90,
    bookValue: 4.20,
    roe: 21.4,
    dividendPerShare: 0.15,  // GHS 0.15 per share, ex-date Jun 24 2026
    revenueGrowth: 18.0,
    profitGrowth: 16.0,
    nplRatio: null,
    car: null,
    forwardPE: 16.4,
    priceTarget: 18.00,
    recommendation: 'HOLD',
    analystNote: 'Dividend yield 1.5% with ex-date June 24 2026. EPS growing 16% per year over 5 years. Well-covered dividend. Brand strength provides moat.',
    dataSource: 'Simply Wall St GSE Analysis Jun 2026',
    lastUpdated: 'Jun 2026',
  },

  TOTAL: {
    fullName: 'TotalEnergies Marketing Ghana Ltd',
    sector: 'Energy',
    description: 'Subsidiary of TotalEnergies SE. Operates fuel retail, lubricants and aviation fuelling across Ghana.',
    eps: 4.20,
    bookValue: 18.50,
    roe: 22.7,
    dividendPerShare: 2.00,
    revenueGrowth: 16.0,
    profitGrowth: 14.0,
    nplRatio: null,
    car: null,
    forwardPE: 9.6,
    priceTarget: 48.00,
    recommendation: 'BUY',
    analystNote: 'Strong parent company backing. Consistent dividend history. Fuel retail growth tied to Ghana\'s economic expansion. Trading below estimated fair value.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jan 2026',
  },

  SOGEGH: {
    fullName: 'Société Générale Ghana Ltd',
    sector: 'Banking',
    description: 'Subsidiary of French banking group Société Générale. Strong in corporate and institutional banking.',
    eps: 1.20,
    bookValue: 5.20,
    roe: 23.1,
    dividendPerShare: 0.40,
    revenueGrowth: 19.0,
    profitGrowth: 22.0,
    nplRatio: 12.5,
    car: 17.8,
    forwardPE: 5.7,
    priceTarget: 8.50,
    recommendation: 'BUY',
    analystNote: 'Stock up 0.88% on June 22. Parent group backing provides stability. Trading at significant discount to estimated fair value.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jan 2026',
  },

  SCB: {
    fullName: 'Standard Chartered Bank Ghana Ltd',
    sector: 'Banking',
    description: 'Subsidiary of global Standard Chartered Group. Focused on corporate, commercial and private banking.',
    eps: 9.50,
    bookValue: 38.00,
    roe: 25.0,
    dividendPerShare: 4.50,
    revenueGrowth: 12.0,
    profitGrowth: 15.0,
    nplRatio: 8.2,
    car: 22.5,
    forwardPE: 7.5,
    priceTarget: 85.00,
    recommendation: 'BUY',
    analystNote: 'Lowest NPL ratio among GSE banks at 8.2%. Strong parent backing. Good dividend yield. Capital adequacy well above regulatory minimum.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jan 2026',
  },

  EGL: {
    fullName: 'Enterprise Group Ltd',
    sector: 'Insurance',
    description: 'Ghana\'s leading financial services conglomerate. Subsidiaries include Enterprise Life, Enterprise Insurance, and Enterprise Trustees.',
    eps: 0.85,
    bookValue: 3.80,
    roe: 22.4,
    dividendPerShare: 0.25,
    revenueGrowth: 20.0,
    profitGrowth: 18.0,
    nplRatio: null,
    car: null,
    forwardPE: 11.8,
    priceTarget: 13.50,
    recommendation: 'BUY',
    analystNote: 'Diversified financial services provide earnings stability. Strong brand. Dividend growth track record. Undervalued relative to peers.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jan 2026',
  },

  BOPP: {
    fullName: 'Benso Oil Palm Plantation Ltd',
    sector: 'Agriculture',
    description: 'Ghana\'s leading palm oil producer. Subsidiary of Wilmar International. Operates a 2,500-hectare estate in the Western Region.',
    eps: 8.50,
    bookValue: 32.00,
    roe: 26.6,
    dividendPerShare: 3.80,
    revenueGrowth: 14.0,
    profitGrowth: 12.0,
    nplRatio: null,
    car: null,
    forwardPE: 10.1,
    priceTarget: 100.00,
    recommendation: 'HOLD',
    analystNote: 'Strong agricultural fundamentals. Dividend yield above sector average. Limited liquidity on the exchange. Solid for income investors.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jan 2026',
  },

  AGA: {
    fullName: 'AngloGold Ashanti (Ord.)',
    sector: 'Mining',
    description: 'One of the world\'s largest gold mining companies. Ghana operations are among its most productive assets globally.',
    eps: 4.80,
    bookValue: 22.00,
    roe: 21.8,
    dividendPerShare: 1.73,  // Q4 2025 dividend $1.73 paid March 2026
    revenueGrowth: 18.0,
    profitGrowth: 22.0,
    nplRatio: null,
    car: null,
    forwardPE: 7.7,
    priceTarget: 52.00,
    recommendation: 'BUY',
    analystNote: 'Global gold price tailwind. Ghana operations are core assets. USD-denominated dividend attractive for GHS-inflation hedge.',
    dataSource: 'SIC Brokerage Daily Report Mar 2026',
    lastUpdated: 'Mar 2026',
  },

  UNIL: {
    fullName: 'Unilever Ghana Ltd',
    sector: 'Consumer Goods',
    description: 'Subsidiary of global Unilever PLC. Manufactures and markets consumer goods including food, home care and personal care products.',
    eps: 0.50,
    bookValue: 3.20,
    roe: 15.6,
    dividendPerShare: 0.20,
    revenueGrowth: 10.0,
    profitGrowth: 8.0,
    nplRatio: null,
    car: null,
    forwardPE: 30.4,
    priceTarget: 14.00,
    recommendation: 'HOLD',
    analystNote: 'Global parent provides stability but local margins under pressure from competition. Trading above estimated fair value at current price.',
    dataSource: 'SIC Brokerage Q4 2025 Report',
    lastUpdated: 'Jan 2026',
  },

  ZEN: {
    fullName: 'ZEN Petroleum Holdings',
    sector: 'Oil & Gas',
    description: 'Indigenous Ghanaian petroleum company listed on the GSE in 2026. Operates in petroleum trading, distribution and storage.',
    eps: 0.85,
    bookValue: 3.50,
    roe: 24.3,
    dividendPerShare: 0.00,
    revenueGrowth: 28.0,
    profitGrowth: 35.0,
    nplRatio: null,
    car: null,
    forwardPE: 11.4,
    priceTarget: 12.50,
    recommendation: 'BUY',
    analystNote: 'New listing with strong growth momentum. Stock up 5.1% recently. No dividend history yet as company reinvests for growth. Watch for first results.',
    dataSource: 'GSE Listing Documents 2026',
    lastUpdated: 'Apr 2026',
  },
};
